config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  root to: 'homes#top'
  get '/home/about' => "homes#about", as: 'about'
  
  delete 'books/:id' => 'books#destroy', as: 'destroy'
  
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
 
 
 
  resources :books do
    resource :favorites , only: [:create , :destroy]
    resources :book_comments, only: [:create , :destroy]
    resources :reviews, only: [:index, :create ]
  end
  
  
  get '/search', to: 'searches#search'
  #検索時に使用するメソッド

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  
before_action :authenticate_user!

def create
	@book = Book.find(params[:book_id])
	@book_comment = BookComment.new(book_comment_params)
	@book_comment.book_id = @book.id
	@book_comment.user_id = current_user.id
 @book_comment_new = BookComment.new
   if @book_comment.save
     # redirect_to book_path(book)
   else
       render 'books/show'
   end
end

 def destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy
    #redirect_to request.referer
    @book_comment_new = BookComment.new
 end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment.html.erb
 <table>
 <% @book.book_comments.each do |book_comment| %>
    <% book_comment_user = book_comment.user %>
    <tr>
    	<td>
    		<%= link_to user_path(book_comment_user), class: "user_#{book_comment_user.id}" do %>
      		<%= attachment_image_tag book_comment_user, :profile_image, :fill, 50, 50, fallback: "no_image.jpg", size: "50x50" %><br>
      		<%= book_comment_user.name %>
    		<% end %>
    	</td>
    	<td><%= book_comment.comment %></td>
    	<% if current_user == book_comment_user %>
      	<td><%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: "btn-sm btn-danger" %></td>
    	<% end %>
    </tr>
  <% end %>
</table>

app/views/book_comments/_form.html.erb
	<%= form_with model:[book,book_comment] do |f| %>
  	<%# ここで非同期にする local true doを消した！ %>
  	<%= f.text_area :comment,  size:"90x5",class: "col-xs-10" %><br>
  	<!-- :の後はカラム名 -->
	  <%= f.submit '送信' %>
	<% end %>

app/views/book_comments/create.js.erb
$('#comment_area').html("<%= j(render 'book_comments/comment', book_comments: @book_comments) %>");
<!--$('#comment_form').html("<%= j(render 'book_comments/form', book: @book, book_comment: @book_comment_new) %>");-->
<!--２行目なくても大丈夫-->
$("textarea").val('')

app/views/book_comments/destroy.js.erb
$('#comment_area').html("<%= j(render 'book_comments/comment',  book_comments: @book_comments) %>");