config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  root to: 'homes#top'
  get '/home/about' => "homes#about", as: 'about'
  
  delete 'books/:id' => 'books#destroy', as: 'destroy'
  
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
 
 
 
  resources :books do
    resource :favorites , only: [:create , :destroy]
    resources :book_comments, only: [:create , :destroy]
    resources :reviews, only: [:index, :create ]
  end
  
  
  get '/search', to: 'searches#search'
  #検索時に使用するメソッド

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy 
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
   
   
   attachment :profile_image
   
   validates :name, length: {minimum: 2, maximum: 20}
   validates :name, uniqueness: true
   validates :introduction, length: {maximum: 50}
   
   def already_favorited?(book)
     self.favorites.exists?(book_id: book.id)
   end
   
   
   
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人
 
 
 
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
   
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @review = Review.new
    @starbook =  Book.find(params[:id])
    #空のモデルの設定
  end
   
    

  
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    
    
  end
  
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: "You have updated user successfully."
    
    else
      
      render :edit
    end
  end
  

 
  
  
  

  
 private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
 
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>

<table class="table">  
<tbody><tr></tr>
<tr>
<th>name</th>
<th><%= user.name %></th>
</tr>
<tr>
<th>introduction</th>
<th><%= user.introduction %></th>
</tr>
  <th>follows</th>
  <th><%= link_to user_followings_path(user) do %>
    <%= user.followings.count %>
    <% end %>
</th>
</tr>
<th>followers</th>
  <th><%= link_to user_followers_path(user) do %>
    <%= user.followers.count %>
    <% end %>
</th>
</tr>

</tbody>
 </table>

<% if user_signed_in? && current_user != user %>
  <% if current_user.following?(user) %>
  <div class="row">
    <%= link_to user_relationships_path(user.id), method: :delete, class:"btn btn-sm btn-primary" do %>
      フォロー外す
    <% end %>
  </div>
  <% else %>
  <div class="row">
    <%= link_to user_relationships_path(user.id), method: :post, class:"btn btn-sm btn-success" do %>
      フォローする
    <% end %> 
  </div>
  <% end %> 
<% else %>
  <div class="row">
  <%= link_to edit_user_path(current_user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %>
  <% end %>
 
</div>
 <% end %>

 

app/views/users/_user.html.erb
 <h2>User info</h2>
 <table class="table">  
  <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>


<tbody><tr></tr>
<tr>
<th>name</th>
<th><%= user.name %></th>
</tr>
<tr>
<th>introduction</th>
<th><%= user.introduction %></th>
</tr>
<th>follows</th>
<th><%= user.followings.count %></th>
</tr>
<th>followers</th>
<th><%= user.followers.count %></th>
</tr>

</tbody>

</table>
<% if user.id == current_user.id %>　
<div class="row">
  <%= link_to edit_user_path(current_user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %>
  <% end %>
  <% else %>
<div class="row">
  <%= link_to edit_user_path(user), class:"btn btn-outline-secondary btn-block fas fa-user-cog" do %>
  
  <% end %> 
  <% end %> 
</div>
 
  

app/views/users/edit.html.erb
<main>
<p id="notice"></p>
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info </h2>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2> <%= @user.errors.count %>error prohibited this obj from being saved:</h2>   
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div> 
  
 <% end %>  
       

<%= form_with model:@user, local:true do |f| %>

    <%= f.label :Name %>
    <%= f.text_field :name, class: "form-control name" %>
    <%= f.label :Image%>
    <%= f.attachment_field :profile_image, class:"form-control-file user_image" %>
    <%= f.label :introduction%>
    <%= f.text_area :introduction, class:"form-control introduction" %><br>
  <div class="form-group">
    <%= f.submit " Update User", class:"btn btn-secondary" %>
 <% end %>

</div>
</div>
</div>
</main>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'users/user', user: @user %>
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
<div class="col-md-8 offset-md-1">
   <h2>Users</h2>
   <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="3"></th>
        </tr>
  	    </thead>
  	  	<tbody>
  	  	  <% @users.each do |user| %>
	  	  	<tr>
	  	  	  <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40"%></td>
	  	  	  <td><%= user.name %></td>
	  	  	  
	      	  <td>フォロー数: <%= user.followings.count %></td>
            <td>フォロワー数: <%= user.followers.count %></td>
            <td><%= render 'relationships/info', user: user %></td>
	  	  	  <td><%= link_to "Show", "/users/#{user.id}" %></td>
	  	  	</tr>
  	  	  <% end %>
  	  	</tbody>
  	  </table>
  	</div>
  </div>
</div>
       

app/views/users/show.html.erb
<main>      
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render 'users/follow', user: @user %>
    
      <h2>New book</h2>
      <%= render 'books/book', book: @book %>
    </div>
    
    
    
    
    <div class="col-md-8 offset-md-1">
      
      <h2>Books</h2>
       <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th> 
            </th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
         
        <% @books.each do |book| %>
        <tbody>
          <tr>
            <td><%= link_to user_path(@user) do %>
            <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
            <% end %></td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
            <td id="favorite_buttons_<%= book.id %>">
　　        <%= render partial: "favorites/favorite", locals: {book: book} %>
　          </td>
            <td>コメント数：<%= @book.book_comments.count %></td>
            <td><%= render 'reviews/form',review: @review, book: @starbook %></td>
            <!--@review,@bookはuserコントローラから来ている-->
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
      
</main>