config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  root to: 'homes#top'
  get '/home/about' => "homes#about", as: 'about'
  
  delete 'books/:id' => 'books#destroy', as: 'destroy'
  
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
 
 
 
  resources :books do
    resource :favorites , only: [:create , :destroy]
    resources :book_comments, only: [:create , :destroy]
    resources :reviews, only: [:index, :create ]
  end
  
  
  get '/search', to: 'searches#search'
  #検索時に使用するメソッド

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
    has_many :reviews, dependent: :destroy



    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: {maximum: 200}
    
    
    


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy 
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
   
   
   attachment :profile_image
   
   validates :name, length: {minimum: 2, maximum: 20}
   validates :name, uniqueness: true
   validates :introduction, length: {maximum: 50}
   
   def already_favorited?(book)
     self.favorites.exists?(book_id: book.id)
   end
   
   
   
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人
 
 
 
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
   
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user  
    @favorite = Favorite.new
    @book_comments = @book.book_comments
    @book_comment = BookComment.new
  end
  
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
    @favorite = Favorite.new
    
  end


  
  def create
      
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    # 
    if @book.save
      
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
     @user = current_user
     @books = Book.all
     render :index
  #renderはredirect_toと異なりアクションを経由せず、そのままビューを出力するので、ビューで使う変数は、renderの前にそのアクション`で定義しないといけない。 ここでは@books=Book.allアクションを定義しておく必要
    end
  end
  # 
  


# findメソッドは、idによってモデルを検索してくれるメソッド
# paramsメソッドは、送信された値の受け渡しをするメソッドparams[:カラム]のように書いて、モデルのカラムを指定してあげることで、送信された値のパラメータからその値を取り出してくれます

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    render "edit"
    else
    redirect_to books_path
    end
  
  end
  # インスタンス変数は、同じクラス内であれば、メソッドを抜け出しても使うことができます！
  # 今回は投稿済みのデータを編集するので、保存されているデータが必要。findメソッドを用いて、データを取得
  #Book.find(params[:id])は、送信されたパラメータの中からidカラムを取り出し、そのidをもとにBookモデルを探している

  
  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
    redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      
    render :edit
    end
  end
  # インスタンス変数で定義し直す
  
  
  def destroy
    @book = Book.find(params[:id])
    
    @book.destroy
    
    redirect_to books_path , notice: "Book was successfully destroyed."
    
  end
  # redirect_toメソッドが実は非常に便利に出来ていて、引数に文字列を渡すことで簡単にflash配列へとメッセージを格納することが可能
  
  private
  # ストロングパラメータ  privateは一種の境界線で、「ここから下はcontrollerの中でしか呼び出せません」という意味   他のアクション（index,show,createなど）を巻き込まないようにprivateはControllerファイルの一番下のendのすぐ上
  def book_params
    params.require(:book).permit(:title, :body)
    
    # require(:book).を削除した
  end
  
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    @book = Book.find(params[:book_id])
    @favorite = current_user.favorites.create(book_id: params[:book_id])
    
    #redirect_back(fallback_location: root_path)→→非同期通信では不要
  end

  def destroy
    @book = Book.find(params[:book_id])
    @favorite = Favorite.find_by(book_id: params[:book_id], user_id: current_user.id)
    @favorite.destroy
    #redirect_back(fallback_location: root_path)→→非同期通信では不要
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end
  
  def create
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def search
    # viewのform_tagにて
    # 選択したmodelの値を@modelに代入。
    @model = params["model"]
    # 選択した検索方法の値を@methodに代入。
    @method = params["method"]
    # 検索ワードを@contentに代入。
    @content = params["content"]
    # @model, @content, @methodを代入した、
    # search_forを@recordsに代入。
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    # 選択したモデルがuserだったら
    if model == 'user'
      # 選択した検索方法がが完全一致だったら
      if method == 'perfect'
        User.where(name: content)
      elsif method == "forward_match"
        User.where("name LIKE?","#{content}%")
      elsif method == "backward_match"
        User.where("name LIKE?","%#{content}")
      # 選択した検索方法がが部分一致だったら
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    # 選択したモデルがbookだったら
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @review = Review.new
    @starbook =  Book.find(params[:id])
    #空のモデルの設定
  end
   
    

  
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    
    
  end
  
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: "You have updated user successfully."
    
    else
      
      render :edit
    end
  end
  

 
  
  
  

  
 private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>

app/views/reviews/_form.html.erb
<!--p class="is-size-4 mb-3">レビューを書く</p>-->
<!--<% if review.errors.any? %>-->
<!--  <div class="notification is-danger">-->
<!--    <h2><%= review.errors.count %>件のエラーがあります。</h2>-->
<!--    <ul>-->
<!--      <% review.errors.full_messages.each do |message| %>-->
<!--        <li><%= message %></li>-->
<!--      <% end %>-->
<!--    </ul>-->
<!--  </div>-->
<!--<% end %>-->
<div class="rating-box mt-3">
  <%= form_with model: review, url: book_reviews_path(book), local: true do |f| %>
    <div class="main-rating">
      <div class="ratings mb-3">
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
        <span class="fa fa-star-o" id="star"></span>
      </div>
    <div class="ml-3 rating-value-display"><span id="rating-value-display">0</span>/5</div>
    </div>
    <%= f.hidden_field :book_id, value: book.id %>
    <%= f.hidden_field :score, id: "rating-value" %>
    <%= f.text_field :content, class: "textarea" %>
    <%= f.submit "保存", class: "button mt-3" %>
    <!--<%= link_to "他のレビューを見る", book_reviews_path(book), class: "button light ml-3 mt-3" %>-->
  <% end %>
</div>

<!--%= javascript_include_tag 'reviews.js' %>-->

app/views/searches/_book.html.erb
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th> </th>
        <th> Title</th>
        <th> Opinion</th>
        <th colspan="3"></th>
      </tr> 
    </thead>
  
  
  
  <tbody>
     <% books.each do |book| %>
	  <tr> 
      <td>
        <%= link_to user_path(book.user) do %>
        <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "40x40"%>
        <% end %>
      </td>
      <td> <%= link_to book.title, book_path(book.id) %></td>
      <td> <%= book.body %></td>
  
    </tr>
      <% end %>
  </tbody>
</table>

app/views/searches/_form.html.erb
<% if user_signed_in? %>
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag 'content' %>
      <%= select_tag 'model', options_for_select({ "User" => "user", "Book" => "book" }) %>
      <%= select_tag 'method', options_for_select({ "完全一致" => "perfect","前方一致" => "forward_match", "後方一致" => "backward_match", "部分一致" => "partial" }) %>
      <%= submit_tag '検索' %>
    <% end %>
<% end %>

app/views/searches/_user.html.erb
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
  
  
  <tbody>
	  <tr> 
	 <% users.each do |user| %>
      <td>
        <%= link_to user_path(user) do %>
        <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40"%>
        <%= user.name %><br>
        <% end %>
      </td>
      <td> <%= user.name %></td>
      
      <td><%= render 'relationships/info', user: user %></td>
	  	<td><%= link_to "Show", "/users/#{user.id}" %></td
    <% end %>
    </tr>
</table>

app/views/searches/search.html.erb
  <div class="col-md-8 offset-md-0">
      
<% if @model == 'user' %>
  <h3>Users search for "<%= @content %>"</h3>
  <%= render 'searches/user', users: @records %>
<% else @model == 'books' %>
  <h3>Books search for "<%= @content %>"</h3>
  <%= render 'searches/book', books: @records %>
<% end %>

</div>