config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'devise/sessions',
    registrations: 'devise/registrations'
  }

  root to: 'homes#top'
  get '/home/about' => "homes#about", as: 'about'
  
  delete 'books/:id' => 'books#destroy', as: 'destroy'
  
  
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  
 
 
 
  resources :books do
    resource :favorites , only: [:create , :destroy]
    resources :book_comments, only: [:create , :destroy]
    resources :reviews, only: [:index, :create ]
  end
  
  
  get '/search', to: 'searches#search'
  #検索時に使用するメソッド

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :user
    has_many :favorites, dependent: :destroy
    has_many :book_comments, dependent: :destroy
    has_many :reviews, dependent: :destroy



    validates :title, presence: true
    validates :body, presence: true
    validates :body, length: {maximum: 200}
    
    
    


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
  
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
  
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy 
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :reviews, dependent: :destroy
   
   
   attachment :profile_image
   
   validates :name, length: {minimum: 2, maximum: 20}
   validates :name, uniqueness: true
   validates :introduction, length: {maximum: 50}
   
   def already_favorited?(book)
     self.favorites.exists?(book_id: book.id)
   end
   
   
   
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  # 被フォロー関係を通じて参照→followed_idをフォローしている人
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # 【class_name: "Relationship"】は省略可能
  has_many :followings, through: :relationships, source: :followed
  # 与フォロー関係を通じて参照→follower_idをフォローしている人
 
 
 
  
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  
  def following?(user)
    followings.include?(user)
  end
  
   
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user  
    @favorite = Favorite.new
    @book_comments = @book.book_comments
    @book_comment = BookComment.new
  end
  
  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
    @favorite = Favorite.new
    
  end


  
  def create
      
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    # 
    if @book.save
      
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
     @user = current_user
     @books = Book.all
     render :index
  #renderはredirect_toと異なりアクションを経由せず、そのままビューを出力するので、ビューで使う変数は、renderの前にそのアクション`で定義しないといけない。 ここでは@books=Book.allアクションを定義しておく必要
    end
  end
  # 
  


# findメソッドは、idによってモデルを検索してくれるメソッド
# paramsメソッドは、送信された値の受け渡しをするメソッドparams[:カラム]のように書いて、モデルのカラムを指定してあげることで、送信された値のパラメータからその値を取り出してくれます

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    render "edit"
    else
    redirect_to books_path
    end
  
  end
  # インスタンス変数は、同じクラス内であれば、メソッドを抜け出しても使うことができます！
  # 今回は投稿済みのデータを編集するので、保存されているデータが必要。findメソッドを用いて、データを取得
  #Book.find(params[:id])は、送信されたパラメータの中からidカラムを取り出し、そのidをもとにBookモデルを探している

  
  def update
    @book = Book.find(params[:id])
    @book.user_id = current_user.id
    if @book.update(book_params)
    redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      
    render :edit
    end
  end
  # インスタンス変数で定義し直す
  
  
  def destroy
    @book = Book.find(params[:id])
    
    @book.destroy
    
    redirect_to books_path , notice: "Book was successfully destroyed."
    
  end
  # redirect_toメソッドが実は非常に便利に出来ていて、引数に文字列を渡すことで簡単にflash配列へとメッセージを格納することが可能
  
  private
  # ストロングパラメータ  privateは一種の境界線で、「ここから下はcontrollerの中でしか呼び出せません」という意味   他のアクション（index,show,createなど）を巻き込まないようにprivateはControllerファイルの一番下のendのすぐ上
  def book_params
    params.require(:book).permit(:title, :body)
    
    # require(:book).を削除した
  end
  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
  
  def about
  end
  
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  end
  
  def create
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  
  def show
    @user = User.find(params[:id])
    @book = Book.new
    @books = @user.books
    @review = Review.new
    @starbook =  Book.find(params[:id])
    #空のモデルの設定
  end
   
    

  
  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    
    
  end
  
  
  def edit
    @user = User.find(params[:id])
    if @user == current_user
        render "edit"
    else
      redirect_to user_path(current_user)
    end
  end
  
  def update
    
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user.id), notice: "You have updated user successfully."
    
    else
      
      render :edit
    end
  end
  

 
  
  
  

  
 private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to root_path, class:"navbar-brand" do %>
          Bookers
          <% end %>
          
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>


          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">

              
              <% if user_signed_in? %>
        
        
              <li>
              <%= link_to user_path(current_user.id), class:"fas fa-home nav-link text-light" do %>
              Home
              <% end %>
              </li>
              
              <li>
              <%= link_to users_path, class:"fas fa-users nav-link text-light"  do %>
              Users
              <% end %>
              </li>
              <li>
              <%= link_to books_path, class:"fas fa-book-open nav-link text-light" do %>
              Books
              <% end %>
              </li>
              <li>
              <%= link_to destroy_user_session_path, method: :delete, class:"fas fa-sign-out-alt nav-link text-light" do %>
              logout
              <% end %>
              </li>
              
            　
              
              <% else %>
              <li>
              <%= link_to root_path, class:"fas fa-home nav-link text-light" do %>
              Home
              <% end %>
              </li>
              
              <li>
              <%= link_to about_path, class:"fas fa-link nav-link text-light" do %>
              About
              <% end %>
              </li>
              <li>
              <%= link_to new_user_registration_path, class:"fas fa-user-plus nav-link text-light" do %>
              sign up
              <% end %>
              </li>
              <li>
              <%= link_to new_user_session_path, class:"fas fa-sign-in-alt nav-link text-light" do %>
              login
              <% end %>
              </li>
                
              
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div class= "search"><%= render 'searches/form'%></div>

    <p class= "notice"><%= notice %></p>
   
  
    <%= yield %>
    
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>